name: Build, Test, and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test

  run_npm_security_scan:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:  
      - name: Run security scan with npm audit
        run: npm audit 

    
  deploy:
    needs: run_npm_security_scan
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Render
      uses: JorgeLNJunior/render-deploy@v1.4.7
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true